name: GitHub Classroom Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - run: sudo apt remove --purge -y python3-pyyaml || true
      - run: pip install --ignore-installed pyyaml
      - run: pip install --force-reinstall -r requirements.txt
      - uses: education/autograding@v1